sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '8'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
# - npm install -g angular-cli
# - npm install -g karma
- npm install
# - ng build

# script: travis_wait 30 npm test
script: ./node_modules/bin/karma start config/karma.conf.js --single-run
